### ISSUE TITLE
Error: Cannot destructure property 'address' of '(intermediate value)' as it is undefined

### ISSUE THREAD

**Issue by victor-homyakov** [mytonwalletorg/mytonwallet#162]
I see the following error in the browser extension MyTonWallet https://chromewebstore.google.com/detail/MyTonWallet%20%C2%B7%20My%20TON%20Wallet/fldfpgipfncgndfolcbkdeeknbbbnhcc

```
Error: Cannot destructure property 'address' of '(intermediate value)' as it is undefined.
    at ConnectorClass.onMessage (chrome-extension://fldfpgipfncgndfolcbkdeeknbbbnhcc/extensionPageScript.js:1574:13)
    at handleMessage (chrome-extension://fldfpgipfncgndfolcbkdeeknbbbnhcc/extensionPageScript.js:1597:15)
```

**Comment by mytonwalletorg** [comment]
Hi @victor-homyakov , are you using the latest (3.0.24) version?

**Comment by victor-homyakov** [comment]
Right now - yes, the latest from the Google Store.

The error is received from the service worker at line https://github.com/mytonwalletorg/mytonwallet/blob/43b0798fa1203018041290697d4d6388ade5466c/src/util/PostMessageConnector.ts#L227 and is thrown at line https://github.com/mytonwalletorg/mytonwallet/blob/43b0798fa1203018041290697d4d6388ade5466c/src/util/PostMessageConnector.ts#L198

I cannot reproduce the error, but it happens somewhere in the service worker when it tries to destructure something like

```ts
const { address, init } = wallet;
```

or

```ts
    const { address, isInitialized: isWalletInitialized, version } = await fetchStoredTonWallet(accountId);
```

or

```ts
async function retrySendBoc({
  network, address, boc, seqno, timestamp,
}
```

or one of similar expressions

**Comment by mytonwalletorg** [comment]
@victor-homyakov Can you still reproduce this with the latest version?

**Comment by victor-homyakov** [comment]
Yes, it still reproduces in 3.0.31. The line numbers have changed slightly since Oct 18 (when 3.0.31 rolled out) but the rest is still the same:

```
Error: Cannot destructure property 'address' of '(intermediate value)' as it is undefined.
    at ConnectorClass.onMessage (chrome-extension://fldfpgipfncgndfolcbkdeeknbbbnhcc/extensionPageScript.js:1584:13)
    at handleMessage (chrome-extension://fldfpgipfncgndfolcbkdeeknbbbnhcc/extensionPageScript.js:1607:15)
```

**Comment by troman29** [comment]
@victor-homyakov Could you give me your contact or write [me](https://t.me/troman29)? To deal with the error faster.

**Comment by tariqmahmood898** [comment]
your project is very nice and use full and could you give me your contact or write [me sms](https://t.me/raymdf)? 
we want to talking about making one Dapp please contact with me

**Comment by mytonwalletorg** [comment]
Fixed. Feel free to create a new issue if the bug persists.
