### ISSUE TITLE
Errors on any page when wallet not inited

### ISSUE THREAD

**Issue by shuva10v** [mytonwalletorg/mytonwallet#27]
I have an error on any page when MyTonWallet is not inited (i.e. wallet neither created nor imported)
```
provider.js:17 Uncaught TypeError: window.ton._destroy is not a function
    at new TonProvider (provider.js:17:40)
    at provider.js:271:18
    at provider.js:307:3
```

Version 1.14.10.
Chrome Version 114.0.5735.133 (Official Build) (arm64)

**Comment by troman29** [comment]
Thanks for the report

**Comment by mytonwalletorg** [comment]
Fixed. Feel free to create a new issue if the bug persists.
